name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  deploy:
    env:
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    timeout-minutes: 10
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 22

        # Node.jsのインストール
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: ./pnpm-lock.yaml
          cache: 'pnpm'

      - name: Install
        run: pnpm install

        
      - name: Deploy worker
        id: deploy-worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_KEY }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            STEAM_API_KEY
            STEAM_USER_ID
            DISCORD_WEBHOOK_URL 
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_USER_ID: ${{ secrets.STEAM_USER_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}